### ISSUE TITLE
Exception when running the ArUcoDetection example scene on Hololens 1.

### ISSUE THREAD

**Issue by robyanne92** [doughtmw/ArUcoDetectionHoloLens-Unity#11]
Hi!! I'm trying to run the ArUcoDetectionHololensUnity project on my Hololens 1. When running the ArUcoDetection scene, I receive the following exception at runtime.

(Translated: "Access violation when reading path 0x000000".)

![image](https://user-images.githubusercontent.com/53224473/92099129-6d434500-edda-11ea-88cc-ff935a81fc15.png)

The exception is thrown from the HoloLensForCV dll. After several tests I noticed that the exception is thrown by the following line in ArUcoMarkerDetection.cs

![image](https://user-images.githubusercontent.com/53224473/92099539-eb9fe700-edda-11ea-8be5-2cffaea126a2.png)

The demo works fine until an ArucoMarker is recognised, than this exception is thrown. These are the last lines from the output console.

![image](https://user-images.githubusercontent.com/53224473/92099784-3ae61780-eddb-11ea-938b-a4c1aa79e5fd.png)

I have used the dlls in the Prebuilt Folder (x86). I have also tried to build the HoloLensForCV project from Visual Studio, but the OpenCv.Hololens.3411 does not exist in the NuGet package store.

Do you have any advice on how to solve it?

Thanks in advance!!

**Comment by robyanne92** [comment]
I have found the NuGet package in the repository. The error is caused by a NullPointerException in class ArUcoMarkerTracker.cpp (line 113). The class tries to access the CoreCameraIntrinsics field of pvSensorFrame, but this field is setted only for Hololens2.

I have personally resolved downgrading the repository to this version https://github.com/doughtmw/ArUcoDetectionHoloLens-Unity/tree/c3b4b2a3d9276ec65a324bb609a6089ceb186c5b

Regards

**Comment by Abdul-Mukit** [comment]
Faced this same problem with Hololens-1.

**Comment by Abdul-Mukit** [comment]
Tried out the downgraded repo as suggested by @robyanne92. Now getting the following exception. Any suggestion would be very helpful. I really needed aruco tracking.
holoLensSensorFrame was nullptr.
![image](https://user-images.githubusercontent.com/29538019/93659450-c5995a00-fa0a-11ea-813b-fcb5969bfcb2.png)

**Comment by Abdul-Mukit** [comment]
Tried out the old repo as suggested by @robyanne92. It worked. Thank you.

**Comment by doughtmw** [comment]
I don't currently have a HoloLens 1 device with me to test the repo, but the recent commit should _hopefully_ address the compatibility issues!

**Comment by Abdul-Mukit** [comment]
Just tried it again with the latest commits. Sorry, this issue still persists for Hololens-1. 
As soon as the first aruco is detected the exception is thrown.

**Comment by doughtmw** [comment]
Hi @Abdul-Mukit! I just wanted to confirm that you are setting the Device Type enum in the Unity project to target the HoloLens 1 (`HL1`) prior to building the sample?
![image](https://user-images.githubusercontent.com/25186390/94024381-56fb2a00-fd85-11ea-84c9-d56d1a330f11.png)

**Comment by Abdul-Mukit** [comment]
Yep, that was the problem. Thank you. Tested with unity 2019 on Hololens-1.

I actually went directly to build and deploy then switched to the old repo where I didn't notice the Device Type field so it never came to my mind.
Thanks a lot for your time and this repo :)
