### ISSUE TITLE
Having problem with git submodule update --init

### ISSUE THREAD

**Issue by Abdul-Mukit** [doughtmw/ArUcoDetectionHoloLens-Unity#12]
Thank you for this repository. It's really helpful. Following is the error that I am getting. Would appreciate any comments.

`Submodule 'HoloLensCamCalib' (https://github.com/doughtmw/HoloLensCamCalib.git) registered for path 'HoloLensCamCalib'
Submodule 'HoloLensForCV' (git@github.com:doughtmw/HoloLensForCV.git) registered for path 'HoloLensForCV'
Cloning into 'D:/Unity Projects/ArUcoDetectionHoloLens-Unity/HoloLensCamCalib'...
Cloning into 'D:/Unity Projects/ArUcoDetectionHoloLens-Unity/HoloLensForCV'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.`

**Comment by Abdul-Mukit** [comment]
Eventually edited the .gitmodules as follows. Don't know if this is correct as eventually, I wasn't able to deploy the project. When deploying the Hololens got stuck in Initializing MediaFrameSourceGroups...

[submodule "HoloLensForCV"]
	path = HoloLensForCV
	url = https://github.com/doughtmw/HoloLensForCV.git
[submodule "NuGet-Package-Creation"]
	path = NuGet-Package-Creation
	url = https://github.com/doughtmw/NuGet-Package-Creation.git
[submodule "HoloLensCamCalib"]
	path = HoloLensCamCalib
	url = https://github.com/doughtmw/HoloLensCamCalib.git

**Comment by doughtmw** [comment]
HI @Abdul-Mukit! Thanks for your interest in this repo. I made a couple of small changes in the most recent commit which hopefully should address the issues with submodule cloning and NuGet package restore. Let me know if you're able to get the samples running now!

**Comment by Abdul-Mukit** [comment]
Sure. I tried it again. This particular problem was resolved in your latest commits.
