### ISSUE TITLE
Trying to understand the drift once aruco detection stops

### ISSUE THREAD

**Issue by Abdul-Mukit** [doughtmw/ArUcoDetectionHoloLens-Unity#15]
Hi,
Thank you, again for this contribution. It would be really helpful if you could help me understand an issue I am having with your app. I wanted to understand why there is a drift/movement in the MarkerCube's pose once detection is stopped by double-tapping. The following is an image that presents this issue. The image is taken after the app is stopped by double tapping and then hololens is moved to a different location. You can see that the cube appears to have drifted to the left significantly. It seems that this is the case whenever hololens is moving around and the cube is set using the last detected world-pose of the marker.
![image](https://user-images.githubusercontent.com/29538019/94354041-c189bf80-003c-11eb-9328-3e86ae45c5cf.png)

A bit of context: 
In my work, I am trying to register a Kinect for Azure camera with Hololens-1 using your app. I first get the world pose of the marker using your app, while keeping the hololens still on a 3D printed structure. After that, I copy that info in my 2nd app to initiate the MarkerCube's world pose. Next, I start holoremoting form the 2nd app and pick up my hololens. While walking around, I see the same problem as mentioned above. The hologram of the cube is not aligned anymore with the marker although I had previously determined the hologram's world pose. 
I did make sure the transforms of MainCamera in your and my scenes are all set to 0. One difference was that you were using a vertical fov of 30 in your scene. In my scene, MRTK sets that to 16 by default. I made sure both are the same in your and my scenes. That seemed to have improved the misalignment along z-axis significantly. 

Any suggestions would be very helpful. Thank you.

**Comment by noxer** [comment]
You can fix this by adding a `WorldAnchor` component to the marker prefab. They describe how that works here: https://docs.microsoft.com/en-us/windows/mixed-reality/out-of-scope/case-study-looking-through-holes-in-your-reality#world-locking-holographic-content

**Comment by Abdul-Mukit** [comment]
Thanks
