### ISSUE TITLE
Mixed Reality Toolkit

### ISSUE THREAD

**Issue by kbamps** [doughtmw/ArUcoDetectionHoloLens-Unity#16]
Hi

Is it possible to use this package in conjugation with the Mixed Reality Toolkit (MRTK) [https://github.com/microsoft/MixedRealityToolkit-Unity](url)?

I would like to use some build-in gesture features.

Thanks in advance!

Best regards

**Comment by Abdul-Mukit** [comment]
@kbamps have made any progress with MRTK? I am about to try the same.

**Comment by kbamps** [comment]
@Abdul-Mukit. Yes it works. However, the MRTK profilier shows that the ArucoDetectionHololens consumes a lot of CPU. (Around 12 fps). This causes a lag when for example you want to click on an UI. Does anyone else have tis problem too?

**Comment by noxer** [comment]
Yes, I solved it (for the most part) by only scanning on every 5th frame. A cleaner way would be to do the processing on a separate thread.

**Comment by kbamps** [comment]
@noxer Thanks for your reply. I managed to do the processing on a seperate thread through the Unity Job System. Now , I yield a fps of 45 to 60 instead of 12.

**Comment by noxer** [comment]
That is awesome! Could you share the code you are using?

**Comment by kbamps** [comment]
@noxer Of course. I forked this repository and will push my changes to it next week. I will keep you posted.

**Comment by noxer** [comment]
That you very much. I'm trying to find a solution for this for a while now.

**Comment by doughtmw** [comment]
Hi @noxer and @kbamps, I've made a couple of quick changes to the `development` branch of the repo to incorporate MRTK interaction, spatial anchors for lost tracking situations and also improve performance. I now use every 3rd frame in the Unity project and include a better async approach to calling the WinRT methods - on the HL2 the sample now runs at ~45-60 FPS performance.
