### ISSUE TITLE
Change camera resolution of Hololens 2??

### ISSUE THREAD

**Issue by mokserpent** [doughtmw/ArUcoDetectionHoloLens-Unity#20]
I run the example in my H2 well , but I need to use the higher resolution of camera
like the 1920*1080 or higher that supported by H2,
Is it possible to change the resolution from 896*504 to higher?? Thanks.

**Comment by doughtmw** [comment]
Hi @mokserpent, sure! You can enforce whichever resolution of the camera you like by modifying the `MediaFrameSourceGroup` file in the `HoloLensForCV` repo ([here is the permalink](https://github.com/doughtmw/HoloLensForCV/blob/7ab30ad3be41390b5a0b363d45230283db8884cd/Shared/HoloLensForCV/MediaFrameSourceGroup.cpp#L555)). You will need to rebuild the `HoloLensForCV` project then copy over all output files into your Unity Assets->Plugins->x86/ARM folder before deploying the app.
