### ISSUE TITLE
Basic Guidance

### ISSUE THREAD

**Issue by Avinash0795** [doughtmw/ArUcoDetectionHoloLens-Unity#22]
Respected People,

 I am currently working on a project (with Hololens 2)
which demands the Arucomarker detection and therefore came across this  
Publication and tried incorporating it in my Project. I followed each and every 
Instruction as per the publication. Upon deploying the app on Hololens 2 
I am able to see only this message saying “ **Initializing MediaFrame Source Groups**”.
When I face my Camera at the Arucomarker available on this Publication 
(https://doughtmw.github.io/posts/ArUco-Detection-HoloLens-4) **I am not able to view the Cube**.
**I believe I am missing some Detail which I am not sure.** 

I just have some doubts and confusions regarding this:

1.	I am basically deploying this app from unity, so does this project need the OpenCV plugin
(https://assetstore.unity.com/packages/tools/integration/opencv-for-unity-21088) from the
Unity Asset store? or is the Nuget package enough?

2.	Does this Project need a Camera Calibration as such for the Aruco Marker detection to Work or should I have to manually
choose the Camera Resolution for the Research Mode?

3.	I understand we need a specific Marker ID for the Aruco Marker to function but I am not
able to see one in your Project?

It would be really a great Help for me if someone could help me with these Questions. Since I am very new to this
Technology, I am having a hard time.

Thank You!

**Comment by mokserpent** [comment]
I just followed the tutorial step by step and then the project run well in my Hololens2 couple weeks ago , so I sure this project
can execute the Aruco marker detection perfectly.
to your questions

1. you can use the existed dll of opencv in the project, and need to set for ARM in the Unity Editor
2. I didn't run the calibration before, so I am not sure whether the calibration need or not . Btw ,I faced the resolution problems now and also need the author's helps.
3. you can download the aruco marker from https://chev.me/arucogen/ or find another source to make it.

some problems I found before including need to set ENABLE_WINMD_SUPPORT definition in the player setting of Unity
and only can choose the ARM to deploy not ARM64.

**Comment by Avinash0795** [comment]
Respected Sir,

Thank you very much for the reply. But somehow I could not figure it out.
I understand that 'MediaFrameSourceGroup' is a class from which the camera could read an Image. But still I am getting the
same Message **'Initializing MediaFrame Source Groups'** once I open the app in and Hololens 2 and nuthing else is happening.

1. Since the project has worked for you and the cube has appeared, could you just tell me why is the Initialisaiton of MediaFrame Source Groups taking so long?
2. Should I change the Resolution of the Camera of Hololens 2? If yes could you just give me a little guidance on how to do it. I have no clue about it.
3. I understand that the cube appears when an Arucomarker from this praticular 6x6 (50, 100, 250, 500) dictionary is detected. But my question is this particular library can generate so many Aruco marker patterns upon changing the ID of the marker. Is it that the cube will appear with any Aruco Pattern from this Library and is independent of Marker ID. Should I have to print the Aruco marker or is it that the camera can detect from the laptop surface?

Please do help me with it.

Thank you!!

**Comment by MediosZ** [comment]
Hi, @Avinash0795 
I met the same problem and solved it by simply change target to ARM from ARM64
It seems that the rebuilt plugins are for ARM, you can try to build them for ARM64.

For your three questions, 
1. Initialization took so long cause some exception was thrown and it just stuck.
2. This problem is not related to the resolution.
3. The cube will appear with any 6x6 marker and is independent of Marker ID. You don't have to print the marker, it can be on screen as well.

**Comment by Avinash0795** [comment]
Thank you very much sir for your Input

**Comment by spany14** [comment]
If anyone is still having the problem of getting stuck at "Initializing MediaFrame Source Groups" , try using 6x6 tags . I tried using april tags 36h11 family, i got the same error.Then I switched to 6x6 it worked like magic
