### ISSUE TITLE
new Mat() Access denied

### ISSUE THREAD

**Issue by ephynes** [doughtmw/ArUcoDetectionHoloLens-Unity#26]
Using OpenCvSharp for HoloLens 2. When I call new Mat() I catch the exception:

System.UnauthorizedAccessException: Failed getting the path of a special folder. Access denied -> System.Environment.GetWindowsFolderPath(System.Int32 folder)

Any suggestions appreciated

**Comment by doughtmw** [comment]
Hi @A00107408! Sorry, I'm not familiar with the OpenCVSharp project and usually use a C++ dll for any processing done in OpenCV.
