### ISSUE TITLE
WorldManager state: Unavailable while accessing _unityCoordinateSystem

### ISSUE THREAD

**Issue by rahidraghav** [doughtmw/ArUcoDetectionHoloLens-Unity#28]
i am unable to retrieve the unity coordinate system (Line 205) as it returns null. I have enable windows mr in XR setting 

 "com.unity.xr.windowsmr": "3.1.6-preview.1"

Please let me know what is missing

**Comment by doughtmw** [comment]
Hi @rahidraghav, I haven't tested the sample with the new Unity XR plugin. Instead, I use the Windows Mixed Reality SDK found under the XR Settings tab of the Player Settings window.
