### ISSUE TITLE
Intrinsics of Research Sensors (Visible Light LF and RF)

### ISSUE THREAD

**Issue by franckies** [doughtmw/ArUcoDetectionHoloLens-Unity#3]
[Vlc_rf_parameters.txt](https://github.com/doughtmw/ArUcoDetectionHoloLens-Unity/files/4358843/Vlc_rf_parameters.txt)
[Vlc_lf_parameters.txt](https://github.com/doughtmw/ArUcoDetectionHoloLens-Unity/files/4358845/Vlc_lf_parameters.txt)

Hello @doughtmw , i've run a camera calibration for the Visible Light LF and RF cameras obtaining the parameters in the attached files. Maybe you can include them in the winmd to let aruco tracking works also with these research sensors.

Moreover, can you please explain me how do you obtain the output files .winmd and .dll 

`
HololensForCV.dll
HololensForCV.winmd
opencv_aruco411.dll
etc...
`
Following the guide in the readme i'm not able to obtain them, I get a lots of errors trying to compile the HoloLensForCV VS solution.
Which nuget packages whould i include? I see OpenCV.HoloLens.411 is pre-included, but using only it the building fails. If i include also OpenCV.UWP.411, the build succeed but when I build on unity and deploy the application something goes wrong.
Thank you in advance.

**Comment by doughtmw** [comment]
Hi, @franckies. Thanks for sharing your calibration parameters! If you're interested in using both the Visible Light LF & RF cameras for tracking, the sample would need to be modified for a stereo tracking-based implementation. I'll work towards putting something together on that end.

As to your issues with compiling the HoloLensForCV library, after building the HoloLensForCV C++ project in Visual Studio (for the HoloLens, use x86 Debug or Release configuration) the output files will appear in the `ArUcoDetectionHoloLens-Unity\HoloLensForCV\$(Debug or Release)\HoloLensForCV` folder. Copy these files to the `ArUcoDetectionHoloLens-Unity\ArUcoDetectionHoloLensUnity\Assets\Plugins\x86` folder and then open your Unity solution and you should be good to go.

**Comment by franckies** [comment]
Hello @doughtmw , thanks again for the reply. Actually, I don't know how i'm now able to build your fork of Hololens for CV correctly using your OpenCV.HoloLens.411.0.0 nuget packet only. I've not used the OpenCV.UWP.411.0.0 nuget package that you suggest to use in the README.

I'm also working toward tracking the aruco using both VL cameras modifying the ArucoTracker.cpp file. For now just inserting this intrinsic parameters for the VL RF camera i'm able to track the markers with just one ambiental camera, however the cubes appear in the space with a big offset w.r.t. markers. I guess something should be changed in the conversion from OpenCV coordinates to Unity Coordinates. 
If I get some news I will let you know.
