### ISSUE TITLE
Slow even after double tap, compared to no aruco detection at all

### ISSUE THREAD

**Issue by nicolas-schreiber** [doughtmw/ArUcoDetectionHoloLens-Unity#32]
Hi,

first of all, thank you for your awesome work with this repo.

I am currently using this repo to display a streamed live pointcloud with an aruco marker as anchor. The performance is quite bad while detecting and simultaneously displaying the pointcloud, understandably.
It gets better when I double tap, however, I found that just displaying the pointcloud without any aruco detection is quite a bit faster even after double tapping. After double tap its about 30fps. Without any aruco stuff  I get to almost 90fps. 
In general it is still smooth when moving around in the pointcloud. It just seems that rendering a new pointcloud is slower.

Do you have any idea how I could diagnose that problem, or even already an idea why that might be?

The pointcloud code is exactly the same in both scenarios.

**Comment by doughtmw** [comment]
Hi @nicolas-schreiber, ArUco tracking was not really optimized too well in this sample so as you observed that is a likely cause of the poor performance. Also, the depth mapper could be optimized by playing around with the `patchRadius`. 

In the coming month or so I plan to release another project with improved ArUco tracking performance for the HoloLens 2 which may be helpful to you.

**Comment by shoukailiang** [comment]
@doughtmw .I will look forward to this project very much

**Comment by Zulex** [comment]
@doughtmw Since this post is from quite some time ago, I was wondering if you have managed to update it to 64 bit?

Thanks for the great project, is super helpful!

**Comment by doughtmw** [comment]
The improved repo for ArUco marker/board tracking on the HoloLens 1/2 is located at: https://github.com/doughtmw/display-calibration-hololens

**Comment by Zulex** [comment]
Thanks for the quick response, appreciate it a bunch!
