### ISSUE TITLE
HI！ What it is  patchRadius?

### ISSUE THREAD

**Issue by pkuma** [doughtmw/ArUcoDetectionHoloLens-Unity#37]
int patchRadius
At DepthPvMapper.cpp
I can find depthrangeFrom and depthrangeTo,which are 200mm and 7500mm
But,i cannot figure out what is patchRadius.
Can u help me ，thank you so much！

**Comment by doughtmw** [comment]
Hi @pkuma, I think you're referring to [this repo](https://github.com/doughtmw/HoloLensForCV-Unity). I believe `patchRadius` has to do with the resolution at which we are sampling the point cloud and projecting to image coordinates.
