### ISSUE TITLE
Cube hovering above marker

### ISSUE THREAD

**Issue by YonatanShaked** [doughtmw/ArUcoDetectionHoloLens-Unity#38]
Hi Mitchell,

I ran the project on my Holo2 (after calibration) and the cube model is hovering above the ArUco marker
I validated that the results are fine in a PC simulation (by rendering the cube on the camera image).

I would appreciate your advice on the matter.

Thanks,

Yonatan

**Comment by loleklel** [comment]
Hi Yonatan,
can you provide me your solution. I have problems with building for HL2. I can try it out and tell you if my calibration worked.

**Comment by Patsufr** [comment]
How can you simulate on your PC

**Comment by doughtmw** [comment]
Hi @YonatanShaked, I'll be releasing an updated repo with improved tracking performance on the HoloLens 2 in the next month or so that will include an additional calibration procedure to help account for the discrepancy in tracking that you've observed.
