### ISSUE TITLE
Support for Unity 2019.3?

### ISSUE THREAD

**Issue by mfrey** [doughtmw/ArUcoDetectionHoloLens-Unity#4]
Hi,

I was wondering if you have (already) tested support for Unity 2019.3 or are aware of any issues migrating to 2019.x from 2018.x? We've upgraded recently from 2018.x to 2019.3 and ran into a few issues such as null pointer exceptions (on arguments) such as:

`"Exception thrown at 0x76CB3AE2 in ArUcoDetectionHoloLensUnity.exe: Microsoft C++ exception: Platform::InvalidArgumentException ^ at memory location 0x0240ECF4. HRESULT:0x80070057 The parameter is incorrect.WinRT information: Argument cannot be null."`

at

`IL2CPP_EXTERN_C IL2CPP_METHOD_ATTR RuntimeObject* MediaFrameSourceGroup_DetectArUcoMarkers_mD7AE9A0A18CAA3E7B1F7F5BDA13E6EFC50DBFCC4 (MediaFrameSourceGroup_t81A62BB7229CDBDE57DACE8362C9A7657B19DEB8 * __this, int32_t ___type0, const RuntimeMethod* method)`

This might be related to our project setup, but before digging to far into I thought I give it a shot and reach out to you.

Thanks in advance!
 Best regards,
  Michael

**Comment by doughtmw** [comment]
Hi Michael! In the most recent commit I've upgraded the project to support Unity 2019.4 LTS versions. If you're still receiving errors it could be due to another issue in the repo.

**Comment by foungyu** [comment]
Hi @doughtmw 
Thanks for sharing your project, it works great with Legacy XR on Unity 2019.4 LTS(2019.4.4f1), however I have same issue with @mfrey on Unity 2019.4 LTS(2019.4.4f1) with Unity new XR Plug-in Management  . Any tip or thought might be able to solve it?
