### ISSUE TITLE
Acess violation HELP

### ISSUE THREAD

**Issue by Patsufr** [doughtmw/ArUcoDetectionHoloLens-Unity#40]
Hi guys,
I need your help. I have this issue in my code and i don't understand why .... Do you have any ideas ? 
Exception thrown at 0x7077C6B6 (opencv_world3411.dll) in GnathiX.exe: 0xC0000005: Access violation writing location 0x00000000.

![image_2021-11-09_155338](https://user-images.githubusercontent.com/39172887/140946994-e26ae624-00d5-486b-af63-f4c3f3530377.png)

**Comment by Patsufr** [comment]
don't put std::vector before your rvec and tvec

**Comment by michbaum** [comment]
Could you elaborate a bit on how you fixed this issue exactly? I ran into exactly the same bug :(

**Comment by michbaum** [comment]
As a heads up for anyone else facing this issue (or similar access violations):
In my case it was resolved by deleting the ARM folder in the unity project and changing the Device type in the Script Holder object, since it is initialized as HL2 and I didn't notice that at the start :)
