### ISSUE TITLE
License commercial usage

### ISSUE THREAD

**Issue by chesslove** [doughtmw/ArUcoDetectionHoloLens-Unity#43]
Hi,
First of all, thank you for your awesome work with this repo.

I am currently using this repo to detect aruco marker attached to movable object. The result is extremely good and i would like to continue using it in the future. But my projects has some commercial usage, so i would like to ask if i can still use this repo in future released products.
Sorry to trouble you because i do not understand what i can do with your included MIT license in project.

Greetings from Japan.

**Comment by spany14** [comment]
Yes, it can be used commercially. You can search google for more information or check the upper window when you open the License file here in GitHub : https://github.com/doughtmw/ArUcoDetectionHoloLens-Unity/blob/master/LICENSE
