### ISSUE TITLE
Project Deployment on HL2 - Error

### ISSUE THREAD

**Issue by FilippoCinotti** [doughtmw/ArUcoDetectionHoloLens-Unity#44]
Hi everyone!
I have followed your guide, but I am still not able to deploy the project on Hololens 2. Am I losing something?
I can't set Device as target debugger and I do not know why. It only happens with this project to me.
![image](https://user-images.githubusercontent.com/63125253/146023660-dac197af-b796-4fb0-b04d-3f52e809e90b.png)

**Comment by doughtmw** [comment]
Hi @FilippoCinotti, it looks like you are missing some requirements for the project as the ArucoTest solution in Visual Studio has not loaded correctly (right pane of above image). Try to right click and reload that project and you will get an error with the requirements that you are missing.

**Comment by FilippoCinotti** [comment]
I have noticed I have both ARM and x86 libraries in the project. Now it is solved
