### ISSUE TITLE
Add prebuilt binaries to Unity project

### ISSUE THREAD

**Issue by qian256** [doughtmw/ArUcoDetectionHoloLens-Unity#6]
Hey Mitchell, I am trying out your ARUCO tracking project here. Great job!
As I navigate through the project, I spent some time figuring out the NuGet package installation and restoration issue. You could consider put the prebuilt binaries in Unity Plugins folder so new users could easier bring up the app.

**Comment by doughtmw** [comment]
Hi Long! That's a great idea. I've also found the NuGet package installation and restoration issues quite challenging at times. I've updated the project with prebuilt binaries for both x86/ARM configurations. Hope all is well with you!
