### ISSUE TITLE
Nuget problem

### ISSUE THREAD

**Issue by mokserpent** [doughtmw/ArUcoDetectionHoloLens-Unity#7]
after PM> Install-Package ..\OpenCV.HoloLens.3411.0.0.nupkg -ProjectName HoloLensForCV

got errors

PM> Install-Package ..\OpenCV.HoloLens.3411.0.0.nupkg -ProjectName HoloLensForCV
Install-Package : Some NuGet packages are missing from the solution. The packages need to be restored in order to build the dependency graph. Restore the packages before perfor
ming any operations.
At line:1 char:1
+ Install-Package ..\OpenCV.HoloLens.3411.0.0.nupkg -ProjectName HoloLe ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Install-Package], InvalidOperationException
    + FullyQualifiedErrorId : NuGetMissingPackages,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
PM> 

Something missing or wrong??

**Comment by doughtmw** [comment]
Hi @mokserpent. That's strange - I haven't run into that error yet. If you are only looking to run the project as is (without any modifications), I've included pre-built binaries which you can copy over to Unity and use!

**Comment by mokserpent** [comment]
Thank you @doughtmw 
The package Manager console show
"Some NuGet packages are missing from this solution. Click to restore from your online package sources". with a "Restore" button
, but no works after pressed the button , and got other messages.

Severity	Code	Description	Project	File	Line	Suppression State
Error		NuGet Package restore failed for project Shared\HoloLensForCV: Unable to find version '3411.0.0' of package 'OpenCV.HoloLens'.
  C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\: Package 'OpenCV.HoloLens.3411.0.0' is not found on source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\'.
  https://api.nuget.org/v3/index.json: Package 'OpenCV.HoloLens.3411.0.0' is not found on source 'https://api.nuget.org/v3/index.json'.
. Please see Error List window for detailed warnings and errors.				

any helps and thanks.

**Comment by doughtmw** [comment]
Hi @mokserpent. There were a few references to Nuget packages from my local repo which made their way into the project somehow and might be causing issues. I made some changes in the most recent commit to address these! Let me know if it works for you.

**Comment by mokserpent** [comment]
Hi @doughtmw 

It works , and nuget show the result

PM> Install-Package ..\OpenCV.HoloLens.3411.0.0.nupkg -ProjectName HoloLensForCV


Attempting to gather dependency information for package 'OpenCV.HoloLens.3411.0.0' with respect to project 'Shared\HoloLensForCV', targeting 'native,Version=v0.0'
Gathering dependency information took 454.71 ms
Attempting to resolve dependencies for package 'OpenCV.HoloLens.3411.0.0' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'OpenCV.HoloLens.3411.0.0'
Resolved actions to install package 'OpenCV.HoloLens.3411.0.0'
Retrieving package 'OpenCV.HoloLens 3411.0.0' from 'C:\Users\mokse\OneDrive\Desktop\ArUcoDetectionHoloLens-Unity-master'.
Adding package 'OpenCV.HoloLens.3411.0.0' to folder 'C:\Users\mokse\OneDrive\Desktop\ArUcoDetectionHoloLens-Unity-master\HoloLensForCV\packages'
Added package 'OpenCV.HoloLens.3411.0.0' to folder 'C:\Users\mokse\OneDrive\Desktop\ArUcoDetectionHoloLens-Unity-master\HoloLensForCV\packages'
Added package 'OpenCV.HoloLens.3411.0.0' to 'packages.config'
Successfully installed 'OpenCV.HoloLens 3411.0.0' to HoloLensForCV
Executing nuget actions took 5.24 sec
Time Elapsed: 00:00:05.9873037

**Comment by doughtmw** [comment]
Awesome! Closing the issue.

**Comment by mokserpent** [comment]
Hi @doughtmw 

I got the other problem, 

when try to compile the HololensForCV project and got a failed message,

3>------ Rebuild All started: Project: HoloLensForCV, Configuration: Debug ARM ------
3>pch.cpp
3>c:\users\mokse\onedrive\desktop\arucodetectionhololens-unity-master\hololensforcv\packages\opencv.hololens.3411.0.0\include\opencv2\calib3d.hpp : error C2220: warning treated as error - no 'object' file generated
3>c:\users\mokse\onedrive\desktop\arucodetectionhololens-unity-master\hololensforcv\packages\opencv.hololens.3411.0.0\include\opencv2\calib3d.hpp : warning C4819: The file contains a character that cannot be represented in the current code page (950). Save the file in Unicode format to prevent data loss
3>Done building project "HoloLensForCV.vcxproj" -- FAILED.
========== Rebuild All: 2 succeeded, 1 failed, 0 skipped ==========

and I add a #pragma in the first line
#pragma warning(disable: 4047)

and then compile well , also shared to you

**Comment by spany14** [comment]
Hi, I have the same problem. Btw I have downloaded the repo this year so that means your changes should have been there already.  The source 'https://nuget.org/v3/index.json' does not have the OpenCV-Hololens pkg anymore. I am not able to find the updated version(if that is the problem).

Edit : I need to build as I  want to implement new functions or functionality.

**Comment by tommensink** [comment]
I have the same issue. @spany14 @doughtmw has this been solved already? I am trying to build for ARM64, but cannot even get it to build for ARM yet. As a Unity developer I am not very proficient with VS, if you can help me further that would be great!

**Comment by spany14** [comment]
@tommensink i think i might be able to help. I was able to build it for ARM, however i could not build it for ARM64 .  I made the following notes when i worked with it.

--> Download HololensforCV submodule from https://github.com/doughtmw/ArUcoDetectionHoloLens-Unity to a new folder.

--> Open HololensforCV.sln in VS2019 (used here by the community)

-->$Install-Package ..\OpenCV.HoloLens.3411.0.0.nupkg
    --> Make sure that the pkg is in this location there

--> Build solution
   --> x86 for HL1 , ARM/ARM64 for HL2

--> Copy the following created files to $<UnityProjectFolder>/Assets/Plugins/ARM(or x86)
      opencv_world3411.dll
      HololensforCV.pri
      HololensforCV.lib
      HololensforCV.exp
      HololensforCV.dll
and
     HololensforCV.winmd to $<UnityProjectFolder>/Assets/Plugin/
       --> Change the platform settings to ARM or x86 for the .dlls in the Unity Inspector.

Edit : The nuget pkg is in the same repository so you do not have to download from the external nuget website

**Comment by doughtmw** [comment]
Thanks @spany14 for your detailed instructions! The Nuget packages sometimes get messed up and aren't included correctly so require some additional steps to fix. As for the ARM64 build, this repo only supports x86 on the HL1 and ARM on the HL2. If you'd like ARM64 support on the HL2 and improved overall performance, check out my new repo ([link](https://github.com/doughtmw/display-calibration-hololens)).

**Comment by IngGabriela** [comment]
Hello! 
I have this error when I try to install OpenCV-OpenCV.HoloLens.3411.0.0.nupkg 
Access to the path 'C:\WINDOWS\LiveKernelReports' is denied.
Access to the path 'C:\WINDOWS\Minidump' is denied.
Access to the path 'C:\WINDOWS\ModemLogs' is denied.
Access to the path 'C:\WINDOWS\prefetch' is denied.
Access to the path 'C:\WINDOWS\ServiceState' is denied.
Access to the path 'C:\WINDOWS\SystemTemp' is denied.
Access to the path 'C:\WINDOWS\Temp' is denied.
Install-Package : Package 'OpenCV.HoloLens 3411.0.0' is not found in the following primary source(s): 'C:\WINDOWS'. Please verify all your online 
package sources are available (OR) package id, version are specified correctly.
At line:1 char:1
+ Install-Package ..\OpenCV.HoloLens.3411.0.0.nupkg
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
    
    
    


What did I do wrong?
