### ISSUE TITLE
^ symbol meaning??

### ISSUE THREAD

**Issue by mokserpent** [doughtmw/ArUcoDetectionHoloLens-Unity#9]
Dear @doughtmw 

I am quite new in C++ , can you tell me what is the symbol '^' in the end of some datatype meaning, like below

Windows::Foundation::Collections::IVector<DetectedArUcoMarker^>^ detectedMarkers
			= ref new Platform::Collections::Vector<DetectedArUcoMarker^>();

Thanks.

**Comment by doughtmw** [comment]
Hi @mokserpent! The `^` is used along with `ref` during the declaration of reference types in the Windows Runtime type system. Here is a [link](https://docs.microsoft.com/en-us/cpp/cppcx/ref-classes-and-structs-c-cx?view=vs-2019) which explains their usage!
